// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWiQBAn1HimXZSLshkzLXBrjcxVExnKjA',
    appId: '1:440399601536:web:82e7d1cd2627313c74ab65',
    messagingSenderId: '440399601536',
    projectId: 'whitelabelapp-6fe66',
    authDomain: 'whitelabelapp-6fe66.firebaseapp.com',
    storageBucket: 'whitelabelapp-6fe66.firebasestorage.app',
    measurementId: 'G-JVFKY6ES74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamuSkHVgrBWIAB6DfyM9G-x0RaxGSfUE',
    appId: '1:440399601536:android:8165e5e3ea81dd9474ab65',
    messagingSenderId: '440399601536',
    projectId: 'whitelabelapp-6fe66',
    storageBucket: 'whitelabelapp-6fe66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7fE6j9H2E62CSOp-ZTAgmddMrSWYCtuw',
    appId: '1:440399601536:ios:ec5357a2827e453574ab65',
    messagingSenderId: '440399601536',
    projectId: 'whitelabelapp-6fe66',
    storageBucket: 'whitelabelapp-6fe66.firebasestorage.app',
    iosBundleId: 'com.example.eventsFeature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7fE6j9H2E62CSOp-ZTAgmddMrSWYCtuw',
    appId: '1:440399601536:ios:ec5357a2827e453574ab65',
    messagingSenderId: '440399601536',
    projectId: 'whitelabelapp-6fe66',
    storageBucket: 'whitelabelapp-6fe66.firebasestorage.app',
    iosBundleId: 'com.example.eventsFeature',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWiQBAn1HimXZSLshkzLXBrjcxVExnKjA',
    appId: '1:440399601536:web:b4c909a13063a0a574ab65',
    messagingSenderId: '440399601536',
    projectId: 'whitelabelapp-6fe66',
    authDomain: 'whitelabelapp-6fe66.firebaseapp.com',
    storageBucket: 'whitelabelapp-6fe66.firebasestorage.app',
    measurementId: 'G-RKB8KFHRET',
  );
}
